In [2]:
import pandas as pd

df = pd.read_excel("marketing_sales_dataset.xlsx")
df.head()

,id,date,region,sales_channel,product_category,customer_segment,season,marketing_budget_usd,ad_spend_online_usd,ad_spend_offline_usd,...,customer_age,customer_satisfaction_score,competitor_price_index,website_traffic,conversion_rate,email_open_rate,social_media_followers,days_since_last_purchase,num_previous_purchases,sales_revenue_usd
0,1,2020-11-12,Riyadh,Retail Store,Cosmetics,Regular,Q4,1664.51,952.30,326.97,...,42,4.5,0.76,1952,0.1193,0.0410,2034,25.0,6,3772.90
1,2,2022-07-05,Dubai,Online,Cosmetics,New,Q3,2452.29,1014.25,414.76,...,24,3.7,1.07,3185,0.0404,0.3166,2058,187.0,7,2091.36
2,3,2020-11-11,Riyadh,Online,Electronics,Regular,Q4,1026.13,328.30,242.72,...,32,2.0,1.18,1304,0.1459,0.3033,417,139.0,3,6201.11
3,4,2022-10-01,Cairo,Online,Electronics,Regular,Q4,1102.86,628.30,204.58,...,62,2.6,0.86,1609,0.0460,0.1138,20618,308.0,6,4911.38
4,5,2023-12-12,Cairo,Retail Store,Food & Beverage,Corporate,Q4,2517.55,777.24,817.88,...,23,3.0,1.01,366639,0.1670,0.1826,57116,97.0,6,7705.73

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           60000 non-null  int64
 1   date                         60000 non-null  object
 2   region                       60000 non-null  object
 3   sales_channel                60000 non-null  object
 4   product_category             60000 non-null  object
 5   customer_segment             60000 non-null  object
 6   season                       60000 non-null  object
 7   marketing_budget_usd         60000 non-null  float64
 8   ad_spend_online_usd          60000 non-null  float64
 9   ad_spend_offline_usd         60000 non-null  float64
 10  num_promotions               60000 non-null  int64
 11  discount_percentage          58192 non-null  float64
 12  num_sales_representatives    60000 non-null  int64
 13  customer_age                 60000 non-null  int64
 14  customer_satisfaction_score  58156 non-null  float64
 15  competitor_price_index       60000 non-null  float64
 16  website_traffic              60000 non-null  int64
 17  conversion_rate              60000 non-null  float64
 18  email_open_rate              58210 non-null  float64
 19  social_media_followers       60000 non-null  int64
 20  days_since_last_purchase     58164 non-null  float64
 21  num_previous_purchases       60000 non-null  int64
 22  sales_revenue_usd            60000 non-null  float64
dtypes: float64(10), int64(7), object(6)
memory usage: 10.5+ MB

In [5]:
df.isnull().sum()
df.duplicated().sum()
df.head()

,id,date,region,sales_channel,product_category,customer_segment,season,marketing_budget_usd,ad_spend_online_usd,ad_spend_offline_usd,...,customer_age,customer_satisfaction_score,competitor_price_index,website_traffic,conversion_rate,email_open_rate,social_media_followers,days_since_last_purchase,num_previous_purchases,sales_revenue_usd
0,1,2020-11-12,Riyadh,Retail Store,Cosmetics,Regular,Q4,1664.51,952.30,326.97,...,42,4.5,0.76,1952,0.1193,0.0410,2034,25.0,6,3772.90
1,2,2022-07-05,Dubai,Online,Cosmetics,New,Q3,2452.29,1014.25,414.76,...,24,3.7,1.07,3185,0.0404,0.3166,2058,187.0,7,2091.36
2,3,2020-11-11,Riyadh,Online,Electronics,Regular,Q4,1026.13,328.30,242.72,...,32,2.0,1.18,1304,0.1459,0.3033,417,139.0,3,6201.11
3,4,2022-10-01,Cairo,Online,Electronics,Regular,Q4,1102.86,628.30,204.58,...,62,2.6,0.86,1609,0.0460,0.1138,20618,308.0,6,4911.38
4,5,2023-12-12,Cairo,Retail Store,Food & Beverage,Corporate,Q4,2517.55,777.24,817.88,...,23,3.0,1.01,366639,0.1670,0.1826,57116,97.0,6,7705.73

In [6]:
df.isnull().sum().sort_values(ascending=False)

customer_satisfaction_score    1844
days_since_last_purchase       1836
discount_percentage            1808
email_open_rate                1790
id                                0
date                              0
region                            0
season                            0
customer_segment                  0
product_category                  0
sales_channel                     0
num_promotions                    0
ad_spend_offline_usd              0
marketing_budget_usd              0
ad_spend_online_usd               0
customer_age                      0
num_sales_representatives         0
website_traffic                   0
competitor_price_index            0
conversion_rate                   0
social_media_followers            0
num_previous_purchases            0
sales_revenue_usd                 0
dtype: int64

In [9]:
# 1. Discount
df['discount_percentage'] = df['discount_percentage'].fillna(0)

# 2. Satisfaction
df['customer_satisfaction_score'] = df['customer_satisfaction_score'].fillna(
    df['customer_satisfaction_score'].median()
)

# 3. Email open rate
df['email_open_rate'] = df['email_open_rate'].fillna(
    df['email_open_rate'].median()
)

# 4. Days since last purchase
df['days_since_last_purchase'] = df['days_since_last_purchase'].fillna(999)

In [10]:
df.isnull().sum()

id                             0
date                           0
region                         0
sales_channel                  0
product_category               0
customer_segment               0
season                         0
marketing_budget_usd           0
ad_spend_online_usd            0
ad_spend_offline_usd           0
num_promotions                 0
discount_percentage            0
num_sales_representatives      0
customer_age                   0
customer_satisfaction_score    0
competitor_price_index         0
website_traffic                0
conversion_rate                0
email_open_rate                0
social_media_followers         0
days_since_last_purchase       0
num_previous_purchases         0
sales_revenue_usd              0
dtype: int64

In [11]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [12]:
df['date'].isnull().sum()

np.int64(0)

In [13]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].str.strip().str.lower()

In [14]:
df[['sales_revenue_usd', 'website_traffic', 'marketing_budget_usd']].describe()

       sales_revenue_usd  website_traffic  marketing_budget_usd
count       60000.000000     6.000000e+04          60000.000000
mean         5911.119206     2.442558e+04          10031.908724
std          5842.470379     6.386642e+04          17300.261988
min           481.080000     1.000000e+02            500.000000
25%          2744.180000     2.961000e+03           2183.567500
50%          4340.050000     8.065000e+03           4922.120000
75%          7091.632500     2.205700e+04          11040.090000
max        190377.350000     2.000000e+06         500000.000000

In [15]:
cols = ['sales_revenue_usd', 'website_traffic', 'marketing_budget_usd']

for col in cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)
    
    df[col] = df[col].clip(lower, upper)

In [16]:
df[cols].describe()

       sales_revenue_usd  website_traffic  marketing_budget_usd
count       60000.000000     60000.000000          60000.000000
mean         5769.193975     22138.134183           9545.749587
std          4652.486315     40028.332078          13074.885483
min          1079.879100       241.990000            500.000000
25%          2744.180000      2961.000000           2183.567500
50%          4340.050000      8065.000000           4922.120000
75%          7091.632500     22057.000000          11040.090000
max         27666.798500    261352.820000          79109.793500

In [17]:
df.shape

(60000, 23)

In [18]:
df.corr(numeric_only=True)['sales_revenue_usd'].sort_values(ascending=False)

sales_revenue_usd              1.000000
marketing_budget_usd           0.670384
ad_spend_online_usd            0.605337
ad_spend_offline_usd           0.583866
num_previous_purchases         0.059690
conversion_rate                0.050064
customer_satisfaction_score    0.047554
num_promotions                 0.044639
website_traffic                0.013852
customer_age                   0.007736
email_open_rate                0.003889
social_media_followers        -0.000639
id                            -0.002118
days_since_last_purchase      -0.002503
num_sales_representatives     -0.004720
competitor_price_index        -0.018473
discount_percentage           -0.027578
Name: sales_revenue_usd, dtype: float64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df = df.copy()

In [21]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           60000 non-null  int64
 1   date                         60000 non-null  datetime64[ns]
 2   region                       60000 non-null  object
 3   sales_channel                60000 non-null  object
 4   product_category             60000 non-null  object
 5   customer_segment             60000 non-null  object
 6   season                       60000 non-null  object
 7   marketing_budget_usd         60000 non-null  float64
 8   ad_spend_online_usd          60000 non-null  float64
 9   ad_spend_offline_usd         60000 non-null  float64
 10  num_promotions               60000 non-null  int64
 11  discount_percentage          60000 non-null  float64
 12  num_sales_representatives    60000 non-null  int64
 13  customer_age                 60000 non-null  int64
 14  customer_satisfaction_score  60000 non-null  float64
 15  competitor_price_index       60000 non-null  float64
 16  website_traffic              60000 non-null  float64
 17  conversion_rate              60000 non-null  float64
 18  email_open_rate              60000 non-null  float64
 19  social_media_followers       60000 non-null  int64
 20  days_since_last_purchase     60000 non-null  float64
 21  num_previous_purchases       60000 non-null  int64
 22  sales_revenue_usd            60000 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(6), object(5)
memory usage: 10.5+ MB

In [23]:
# Feature engineering
df['total_ad_spend'] = df['ad_spend_online_usd'] + df['ad_spend_offline_usd']

df['roi'] = df['sales_revenue_usd'] / df['total_ad_spend']

df['engagement'] = df['website_traffic'] * df['conversion_rate']

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

In [24]:
df.columns

Index(['id', 'date', 'region', 'sales_channel', 'product_category',
       'customer_segment', 'season', 'marketing_budget_usd',
       'ad_spend_online_usd', 'ad_spend_offline_usd', 'num_promotions',
       'discount_percentage', 'num_sales_representatives', 'customer_age',
       'customer_satisfaction_score', 'competitor_price_index',
       'website_traffic', 'conversion_rate', 'email_open_rate',
       'social_media_followers', 'days_since_last_purchase',
       'num_previous_purchases', 'sales_revenue_usd', 'total_ad_spend', 'roi',
       'engagement', 'year', 'month'],
      dtype='object')

In [25]:
df['roi'].describe()

count    60000.000000
mean         2.479641
std          3.564237
min          0.074067
25%          0.680973
50%          1.300445
75%          2.753907
max         72.315890
Name: roi, dtype: float64

In [26]:
df['roi'] = df['roi'].clip(0, df['roi'].quantile(0.99))

In [27]:
df['roi'].describe()

count    60000.000000
mean         2.404276
std          3.029617
min          0.074067
25%          0.680973
50%          1.300445
75%          2.753907
max         18.030759
Name: roi, dtype: float64

In [28]:
summary = {
    "Total Revenue": df['sales_revenue_usd'].sum(),
    "Average Revenue": df['sales_revenue_usd'].mean(),
    "Total Customers": df['id'].nunique(),
    "Average ROI": df['roi'].mean()
}

print(summary)

{'Total Revenue': np.float64(346151638.51), 'Average Revenue': np.float64(5769.193975166667), 'Total Customers': 60000, 'Average ROI': np.float64(2.404276094611461)}

In [29]:
df.to_excel("cleaned_data_final.xlsx", index=False)

In [31]:
def full_pipeline(file):
    import pandas as pd
    
    # Load data
    df = pd.read_excel(file)
    df = df.copy()
    
    # ---------------------------
    # 1. Handle Missing Values
    # ---------------------------
    df['discount_percentage'] = df['discount_percentage'].fillna(0)
    
    df['customer_satisfaction_score'] = df['customer_satisfaction_score'].fillna(
        df['customer_satisfaction_score'].median()
    )
    
    df['email_open_rate'] = df['email_open_rate'].fillna(
        df['email_open_rate'].median()
    )
    
    df['days_since_last_purchase'] = df['days_since_last_purchase'].fillna(999)
    
    # ---------------------------
    # 2. Fix Date
    # ---------------------------
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    
    # ---------------------------
    # 3. Clean Text Columns
    # ---------------------------
    cat_cols = df.select_dtypes(include='object').columns
    for col in cat_cols:
        df[col] = df[col].str.strip().str.lower()
    
    # ---------------------------
    # 4. Handle Outliers (Capping)
    # ---------------------------
    cols = ['sales_revenue_usd', 'website_traffic', 'marketing_budget_usd']
    
    for col in cols:
        lower = df[col].quantile(0.01)
        upper = df[col].quantile(0.99)
        df[col] = df[col].clip(lower, upper)
    
    # ---------------------------
    # 5. Feature Engineering
    # ---------------------------
    df['total_ad_spend'] = df['ad_spend_online_usd'] + df['ad_spend_offline_usd']
    
    df['roi'] = df['sales_revenue_usd'] / df['total_ad_spend']
    
    df['engagement'] = df['website_traffic'] * df['conversion_rate']
    
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    
    # ---------------------------
    # 6. Fix ROI Issues
    # ---------------------------
    df['roi'] = df['roi'].replace([float('inf'), -float('inf')], 0)
    df['roi'] = df['roi'].clip(0, df['roi'].quantile(0.99))
    
    # ---------------------------
    # 7. Final Cleanup
    # ---------------------------
    df = df.drop_duplicates()
    
    return df

In [33]:
df = full_pipeline("marketing_sales_dataset.xlsx")

In [34]:
df.head()

,id,date,region,sales_channel,product_category,customer_segment,season,marketing_budget_usd,ad_spend_online_usd,ad_spend_offline_usd,...,email_open_rate,social_media_followers,days_since_last_purchase,num_previous_purchases,sales_revenue_usd,total_ad_spend,roi,engagement,year,month
0,1,2020-11-12,riyadh,retail store,cosmetics,regular,q4,1664.51,952.30,326.97,...,0.0410,2034,25.0,6,3772.90,1279.27,2.949260,232.87360,2020,11
1,2,2022-07-05,dubai,online,cosmetics,new,q3,2452.29,1014.25,414.76,...,0.3166,2058,187.0,7,2091.36,1429.01,1.463503,128.67400,2022,7
2,3,2020-11-11,riyadh,online,electronics,regular,q4,1026.13,328.30,242.72,...,0.3033,417,139.0,3,6201.11,571.02,10.859707,190.25360,2020,11
3,4,2022-10-01,cairo,online,electronics,regular,q4,1102.86,628.30,204.58,...,0.1138,20618,308.0,6,4911.38,832.88,5.896864,74.01400,2022,10
4,5,2023-12-12,cairo,retail store,food & beverage,corporate,q4,2517.55,777.24,817.88,...,0.1826,57116,97.0,6,7705.73,1595.12,4.830815,43645.92094,2023,12

In [35]:
df.shape
df.columns
df.head()

,id,date,region,sales_channel,product_category,customer_segment,season,marketing_budget_usd,ad_spend_online_usd,ad_spend_offline_usd,...,email_open_rate,social_media_followers,days_since_last_purchase,num_previous_purchases,sales_revenue_usd,total_ad_spend,roi,engagement,year,month
0,1,2020-11-12,riyadh,retail store,cosmetics,regular,q4,1664.51,952.30,326.97,...,0.0410,2034,25.0,6,3772.90,1279.27,2.949260,232.87360,2020,11
1,2,2022-07-05,dubai,online,cosmetics,new,q3,2452.29,1014.25,414.76,...,0.3166,2058,187.0,7,2091.36,1429.01,1.463503,128.67400,2022,7
2,3,2020-11-11,riyadh,online,electronics,regular,q4,1026.13,328.30,242.72,...,0.3033,417,139.0,3,6201.11,571.02,10.859707,190.25360,2020,11
3,4,2022-10-01,cairo,online,electronics,regular,q4,1102.86,628.30,204.58,...,0.1138,20618,308.0,6,4911.38,832.88,5.896864,74.01400,2022,10
4,5,2023-12-12,cairo,retail store,food & beverage,corporate,q4,2517.55,777.24,817.88,...,0.1826,57116,97.0,6,7705.73,1595.12,4.830815,43645.92094,2023,12

In [36]:
df[['total_ad_spend', 'roi', 'engagement', 'year', 'month']].head()

   total_ad_spend        roi   engagement  year  month
0         1279.27   2.949260    232.87360  2020     11
1         1429.01   1.463503    128.67400  2022      7
2          571.02  10.859707    190.25360  2020     11
3          832.88   5.896864     74.01400  2022     10
4         1595.12   4.830815  43645.92094  2023     12

In [37]:
df['engagement'].describe()

count     60000.000000
mean       2021.256019
std        4597.980466
min           0.000000
25%         189.279800
50%         586.149200
75%        1793.603775
max      103182.093336
Name: engagement, dtype: float64

In [38]:
df['engagement'] = df['engagement'].clip(0, df['engagement'].quantile(0.99))

In [39]:
df['engagement'].describe()

count    60000.000000
mean      1901.185869
std       3628.586916
min          0.000000
25%        189.279800
50%        586.149200
75%       1793.603775
max      22805.209812
Name: engagement, dtype: float64

In [40]:
df.describe()

,id,date,marketing_budget_usd,ad_spend_online_usd,ad_spend_offline_usd,num_promotions,discount_percentage,num_sales_representatives,customer_age,customer_satisfaction_score,...,email_open_rate,social_media_followers,days_since_last_purchase,num_previous_purchases,sales_revenue_usd,total_ad_spend,roi,engagement,year,month
count,60000.000000,60000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,6.000000e+04,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,30000.500000,2022-01-01 17:39:10.080000256,9545.749587,4018.443457,2508.806999,4.492683,19.445650,24.931683,45.796283,3.495843,...,0.230338,2.219776e+04,206.471700,4.984750,5769.193975,6527.250456,2.404276,1901.185869,2021.505117,6.507500
min,1.000000,2020-01-01 00:00:00,500.000000,100.140000,50.030000,0.000000,0.000000,1.000000,18.000000,2.000000,...,0.002400,1.000000e+02,0.000000,0.000000,1079.879100,153.930000,0.074067,0.000000,2020.000000,1.000000
25%,15000.750000,2020-12-31 00:00:00,2183.567500,816.827500,486.857500,2.000000,9.200000,13.000000,31.000000,2.800000,...,0.148000,7.710000e+02,92.000000,3.000000,2744.180000,1366.195000,0.680973,189.279800,2020.000000,4.000000
50%,30000.500000,2022-01-07 00:00:00,4922.120000,1876.355000,1152.395000,4.000000,19.400000,25.000000,46.000000,3.500000,...,0.216600,2.971000e+03,187.000000,5.000000,4340.050000,3106.775000,1.300445,586.149200,2022.000000,7.000000
75%,45000.250000,2023-01-03 00:00:00,11040.090000,4336.847500,2676.797500,7.000000,29.700000,37.000000,60.000000,4.200000,...,0.298000,1.138675e+04,281.000000,6.000000,7091.632500,7085.832500,2.753907,1793.603775,2023.000000,10.000000
max,60000.000000,2023-12-31 00:00:00,79109.793500,235211.830000,138327.250000,9.000000,40.000000,49.000000,74.000000,5.000000,...,0.753700,5.000000e+06,999.000000,17.000000,27666.798500,373539.080000,18.030759,22805.209812,2023.000000,12.000000
std,17320.652413,NaN,13074.885483,7308.813859,4668.240020,2.873120,11.838702,14.179356,16.477802,0.853588,...,0.110821,1.157277e+05,174.942715,2.231472,4652.486315,11656.737524,3.029617,3628.586916,1.119685,3.439105

In [42]:
summary = {
    "Total Revenue": float(df['sales_revenue_usd'].sum()),
    "Average Revenue": float(df['sales_revenue_usd'].mean()),
    "Average ROI": float(df['roi'].mean())
}

print(summary)

{'Total Revenue': 346151638.51, 'Average Revenue': 5769.193975166667, 'Average ROI': 2.404276094611461}

In [43]:
df.to_excel("cleaned_data_final.xlsx", index=False)